name: Java CI with gradle

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
          cache: "gradle"
      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew build --no-daemon
